name: just_weather
version: 1.0.0+1
publish_to: none
description: DVT Weather app test.
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  geolocator_windows: ^0.1.0
  shimmer: ^2.0.0
  mdi: ^5.0.0-nullsafety.0
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
